name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
- uses: actions/checkout@v4

- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.2' # Ajusta esto a tu versión de PHP
    extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, zip
    
- name: Validate composer.json and composer.lock
  run: composer validate --strict

- name: Install Dependencies
  run: |
    composer install --prefer-dist --no-progress
    # Si lo anterior falla, intentar:
    # composer update --no-progress
